name: Deploy GitHub Pages

on:

# Ежедневное обновление в 00:00 UTC (03:00 МСК)
  # schedule:
  #   - cron: "0 0 * * *"

  # Запускается после завершения Frequent Update (закомментировано - не нужно пересобирать сайт после каждого обновления файлов)
  # workflow_run:
  #   workflows: ["Frequent Update"]
  #   types: [completed]
  
  
  
  # Старый вариант (закомментирован):
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      # - 'githubmirror/**'
      - '.github/workflows/jekyll-docker.yml'
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
          future: true
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
